#!/bin/bash
set -euo pipefail

#==============================================================#
# File      :   get
# Ctime     :   2023-10-05
# Mtime     :   2023-10-05
# Desc      :   Get Prometheus Tarballs
# Path      :   bin/get
# Depend    :   curl tar gzip
# Copyright (C) 2018-2023 Ruohang Feng
#==============================================================#


#--------------------------------------------------------------#
# Param
#--------------------------------------------------------------#
PROG_DIR="$(cd $(dirname $0) && pwd)"
PROG_NAME="$(basename $0)"
PROJ_DIR=$(dirname $PROG_DIR)
TARBALL_DIR="${PROJ_DIR}/tarball"


#==============================================================#
# color log util
#==============================================================#
__CN='\033[0m'    # no color
__CB='\033[0;30m' # black
__CR='\033[0;31m' # red
__CG='\033[0;32m' # green
__CY='\033[0;33m' # yellow
__CB='\033[0;34m' # blue
__CM='\033[0;35m' # magenta
__CC='\033[0;36m' # cyan
__CW='\033[0;37m' # white
function log_info() {  printf "[${__CG} OK ${__CN}] ${__CG}$*${__CN}\n";   }
function log_warn() {  printf "[${__CY}WARN${__CN}] ${__CY}$*${__CN}\n";   }
function log_error() { printf "[${__CR}FAIL${__CN}] ${__CR}$*${__CN}\n";   }
function log_debug() { printf "[${__CB}HINT${__CN}] ${__CB}$*${__CN}\n"; }
function log_input() { printf "[${__CM} IN ${__CN}] ${__CM}$*\n=> ${__CN}"; }
function log_hint()  { printf "${__CB}$*${__CN}\n"; }
#==============================================================#

function get_file_size(){
  local file=$1
  if [[ -f ${file} ]]; then
    echo $(stat -c %s ${file})
  else
    echo 0
  fi
}

# download file from url, if file already exists with same size, skip download
function download_file(){
  local data_url=$1
  local data_file=$2

  if [[ -f ${data_file} ]]; then
    size=$(get_file_size ${data_file})
    log_warn "data file exists, size: ${size} , path: ${data_file}"
    curl_size=$(curl -sI ${data_url} | grep -i 'Content-Length' | awk '{print $2}' | tr -d '\r')
    if [[ ${size} -eq ${curl_size} ]]; then
      log_info "data url file has same size: ${curl_size} , skip downloading ${data_url}"
      return 0
    else
      log_warn "data url file size ${curl_size} != local ${size}, downloading ${data_url}"
      log_info "$ curl ${data_url} -o ${data_file}"
      curl ${data_url} -o ${data_file}
      return $?
    fi
  else
    log_info "download ${data_url} to ${data_file}"
    log_info "$ curl ${data_url} -o ${data_file}"
    curl ${data_url} -o ${data_file}
    return $?
  fi
}



download_file https://github.com/prometheus/prometheus/releases/download/v2.47.1/prometheus-2.47.1.linux-amd64.tar.gz                                   ${TARBALL_DIR}/prometheus-2.47.1.freebsd-amd64.tar.gz
download_file https://github.com/prometheus/alertmanager/releases/download/v0.26.0/alertmanager-0.26.0.linux-amd64.tar.gz                               ${TARBALL_DIR}/alertmanager-0.26.0.linux-amd64.tar.gz
download_file https://github.com/prometheus/pushgateway/releases/download/v1.6.2/pushgateway-1.6.2.linux-amd64.tar.gz                                   ${TARBALL_DIR}/pushgateway-1.6.2.linux-amd64.tar.gz
download_file https://github.com/prometheus/blackbox_exporter/releases/download/v0.24.0/blackbox_exporter-0.24.0.linux-amd64.tar.gz                     ${TARBALL_DIR}/blackbox_exporter-0.24.0.linux-amd64.tar.gz
download_file https://github.com/prometheus/node_exporter/releases/download/v1.6.1/node_exporter-1.6.1.linux-amd64.tar.gz                               ${TARBALL_DIR}/node_exporter-1.6.1.linux-amd64.tar.gz
download_file https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.11.0/nginx-prometheus-exporter_0.11.0_linux_amd64.tar.gz       ${TARBALL_DIR}/nginx-prometheus-exporter_0.11.0_linux_amd64.tar.gz
download_file https://github.com/Vonng/pg_exporter/releases/download/v0.5.0/pg_exporter_v0.5.0_linux-amd64.tar.gz                                       ${TARBALL_DIR}/pg_exporter_v0.5.0_linux-amd64.tar.gz
download_file https://github.com/prometheus/mysqld_exporter/releases/download/v0.15.0/mysqld_exporter-0.15.0.linux-amd64.tar.gz                         ${TARBALL_DIR}/mysqld_exporter-0.15.0.linux-amd64.tar.gz
download_file https://github.com/danielqsj/kafka_exporter/releases/download/v1.7.0/kafka_exporter-1.7.0.linux-amd64.tar.gz                              ${TARBALL_DIR}/kafka_exporter-1.7.0.linux-amd64.tar.gz
download_file https://github.com/percona/mongodb_exporter/releases/download/v0.39.0/mongodb_exporter-0.39.0.linux-amd64.tar.gz                          ${TARBALL_DIR}/mongodb_exporter-0.39.0.linux-amd64.tar.gz
download_file https://github.com/gen2brain/keepalived_exporter/releases/download/0.5.0/keepalived_exporter-0.5.0-amd64.tar.gz                           ${TARBALL_DIR}/keepalived_exporter-0.5.0-amd64.tar.gz
download_file https://github.com/oliver006/redis_exporter/releases/download/v1.54.0/redis_exporter-v1.54.0.linux-amd64.tar.gz                           ${TARBALL_DIR}/redis_exporter-v1.54.0.linux-amd64.tar.gz


#v_prometheus=2.49.1           https://github.com/prometheus/prometheus/releases/download/v2.49.1/prometheus-2.49.1.linux-amd64.tar.gz
#v_alertmanager=0.26.0         https://github.com/prometheus/alertmanager/releases/download/v0.26.0/alertmanager-0.26.0.linux-amd64.tar.gz
#v_pushgateway=1.7.0           https://github.com/prometheus/pushgateway/releases/download/v1.7.0/pushgateway-1.7.0.linux-amd64.tar.gz
#v_blackbox_exporter=0.24.0    https://github.com/prometheus/blackbox_exporter/releases/download/v0.24.0/blackbox_exporter-0.24.0.linux-amd64.tar.gz
#v_node_exporter=1.7.0         https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
#v_nginx_exporter=1.1.0        https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v1.1.0/nginx-prometheus-exporter_1.1.0_linux_amd64.tar.gz
#v_pg_exporter=0.6.1           https://github.com/Vonng/pg_exporter/releases/download/v0.6.1/pg_exporter-v0.6.1.linux-amd64.tar.gz
#v_mysqld_exporter=0.15.1      https://github.com/prometheus/mysqld_exporter/releases/download/v0.15.1/mysqld_exporter-0.15.1.linux-amd64.tar.gz
#v_kafka_exporter=1.7.0        https://github.com/danielqsj/kafka_exporter/releases/download/v1.7.0/kafka_exporter-1.7.0.linux-amd64.tar.gz
#v_mongodb_exporter=0.40.0     https://github.com/percona/mongodb_exporter/releases/download/v0.40.0/mongodb_exporter-0.40.0.linux-amd64.tar.gz
#v_keepalived_exporter=0.7.0   https://github.com/gen2brain/keepalived_exporter/releases/download/v0.7.0/keepalived_exporter-0.7.0-amd64.tar.gz
#v_redis_exporter=1.57.0       https://github.com/oliver006/redis_exporter/releases/download/v1.57.0/redis_exporter-v1.57.0.linux-amd64.tar.gz
#v_pgbackrest_exporter=0.16.2  https://github.com/woblerr/pgbackrest_exporter/releases/download/v0.16.2/pgbackrest_exporter-0.16.2-linux-x86_64.tar.gz